//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPhanQuyen.Areas.Admin.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Permission
    {
        public string UserGroupID { get; set; }
        public string RoleID { get; set; }
    }
}
